### ISSUE TITLE
Home page: Instead of "Upcoming Events" just say "Events" and feature most recent event

### ISSUE THREAD

**Issue by kanarinka** [engagementgamelab/boston-civic-media#102]
Like Issue #101 said, let's get rid of the past/upcoming distinction. The home pge should just show a link to the most recent event that we held and the header text should say "Events" instead of "Upcoming Events"

**Comment by rebeccamichelson** [comment]
@kanarinka instead of "Events" this says "Featured Event" but it looks fine to me. I am moving it to closed.
