### ISSUE TITLE
Climate Courses page: show faculty name & institution along with course title

### ISSUE THREAD

**Issue by kanarinka** [engagementgamelab/boston-civic-media#106]
We may end up not having time for this but it would be great to show the faculty name and their institution along with the course title. One of the things that we want to communicate with the home page is that this is a cross-institutional endeavor and also that the courses are not "ours" in the sense that BCM runs its own courses.

@esalling23 is this a crazy amount of work? if so, not worth it. But if this is easy it is worth doing

**Comment by esalling23** [comment]
@kanarinka Not quite sure what to do here - sounds pretty straightforward but where my confusion is coming from is that there is already an institution and instructor name displayed with the courses, I included the screenshot below for this. 
<img width="1064" alt="screen shot 2017-07-21 at 3 00 40 pm" src="https://user-images.githubusercontent.com/11821504/28478248-992c8038-6e25-11e7-9275-d92580988261.png">
Are you saying you want the institution/faculty name on the left in the list of courses, along with the course titles?

**Comment by kanarinka** [comment]
You know what? I'm not sure what I meant either ! Let's just leave this as
is
