### ISSUE TITLE
Eventpage: list past events in reverse chronological order

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/boston-civic-media#11]
This is also linked to #13 since we might want to combine these or at least tackle them simultaneously. That said, I think making sure the code is in place to display things in reverse chron. can be done regardless.

**Comment by jpailthorpe** [comment]
past event block is not displaying in reverse chron. upcoming might be, but figured i would move this issue back instead of opening a new one.

**Comment by jpailthorpe** [comment]
![screen shot 2017-06-05 at 5 11 35 pm](https://cloud.githubusercontent.com/assets/10051544/26803445/3a15c8c0-4a12-11e7-9c9c-d3340d78814a.png)

**Comment by jpailthorpe** [comment]
fixed and ready for prod.

**Comment by jpailthorpe** [comment]
up on production
