### ISSUE TITLE
need to add + modify faculty name in course listing

### ISSUE THREAD

**Issue by gmugar** [engagementgamelab/boston-civic-media#110]
it looks like I can only add names that existing in a database...not sure where that is or how to modify it.

**Comment by esalling23** [comment]
@gmugar That field pulls from the Filters with category 'Faculty Member'. The Filters tab is under Syllabi on the navigation bar in keystone, see the picture below. 
<img width="944" alt="screen shot 2017-08-08 at 1 22 59 pm" src="https://user-images.githubusercontent.com/11821504/29085252-b9bcc68a-7c3c-11e7-871f-30207d19369b.png">
