### ISSUE TITLE
EventPage: Add documentation link in event page

### ISSUE THREAD

**Issue by codeworthy** [engagementgamelab/boston-civic-media#16]
Since Hackpad is closing down, let's change the "hackpad link" to "documentation" in the Events pages. Example: https://bostoncivic.media/events/civic-media-impact-and-assessmentlesspgreaterapril-2016lesspgreater.

**Comment by jpailthorpe** [comment]
With the updated design, we did not include entries to these documentation links. That said, you can easily add links to these documents via the long description markdown field under the event. If you bold and hyperlink it, it will look like this:
![screen shot 2017-06-08 at 2 27 14 pm](https://user-images.githubusercontent.com/10051544/26944444-b1c881f0-4c56-11e7-84d5-94d5e7e45999.png)

you can of course title the name of the link anything you want and link to any url (here I am linking to the hackpad backup google doc in the drive).
