### ISSUE TITLE
Courses: Specific college enrollment information is much too bloated and not consistent, which will create erratic design. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/boston-civic-media#26]
right now, the current courses mockup [does not include course registration information laid out in the google doc. ](https://docs.google.com/a/elab.emerson.edu/document/d/11CX6VEDseO77IEB_O9lmvUBgw5U-j0b7coGOuTK_FdA/edit?usp=sharing)

This information cannot be in the displayed block with the course information because it is so wildly different, and it would be very difficult to wrangle within a good design. Because of this, we can do three options, from easiest to hardest:

1.  Just have the enroll button link out to the correlated page where this information is contained. 

2. If this is not an option, we suggest re-writing this information into more of a descriptive paragraph that generalizes how to register rather than a step by step detailed list going into intense detail, making it the same average length as the course description. 

3. Last option is we make another section within the course page below the content displayed that lists each institution with enrollment information contained within accordion/expandable divs. **For this, we will need a header text (like, "enrollment information") and then a short description explaining what this section details and how to use it.** This is the messiest approach in my opinion, because the formatting will be very different for each school.

**Comment by aidanrae** [comment]
Considering the enrollment information is available on the respective academic websites, I think it's overkill to write it out in steps. I also don't think it's useful in this context, unless there are some pertinent stipulations like, you must register before a certain date, etc.

**Comment by kanarinka** [comment]
@jpailthorpe and @aidanrae -- I know this is not ideal from an information design standpoint, but we need to include this information on our site to show the funder that we are trying to help facilitate cross-registration. So let's rule out option #2 because it doesn't meet this criteria. 

For option #1 - do you mean making a separate page on our site for the info? Or do you mean linking to the institution's site?

My preference would be for something that is 1) easy/doesn't take too much dev time to create and 2) easily updatable by a project manager without needing to request dev time. For example, imagine that we will add a new institution every couple months and we would need to add their registration info. Which of options #1 or #3 is better for that criteria?

**Comment by jpailthorpe** [comment]
This is really helpful! to clarify, #1 would link out to institution site, but based on your feedback, it seems like this wouldn't solve the problem.

Not sure if I explained #2 well, but wouldn't be generic but actually institution specific. It's more about someone taking these bulleted lists and language that is excruciatingly detailed and write a few sentences or so for each institution and explain in human speak what you need to do to register. This can then go right in the vertical block under the course desc.

If that doesn't work, we can just have enrollment info below the course description block in a new section that is independent of the course selector list, and organized by institution.  Aidan and I will work on this today. Both would be easy to implement and update.

**Comment by jpailthorpe** [comment]
Aidan will show some option visuals

**Comment by kanarinka** [comment]
OK yes - I think it'd be good to stick with the excruciating language (sorry :() and go with option #3.

**Comment by jpailthorpe** [comment]
two visual mocks below. You can see that the latter version includes everything from the google doc. Both include a icongraphic section detailing a simplified process on how a student would take steps to register. 


![1024_courses](https://cloud.githubusercontent.com/assets/10051544/26426198/992550a4-40a5-11e7-9cbe-a8392ca30759.png)

![1024_courses alt](https://cloud.githubusercontent.com/assets/10051544/26426201/9d33365c-40a5-11e7-89d2-c757f8bd3068.png)

**Comment by kanarinka** [comment]
This looks great (or, as good as messy information can look, let's say :) - let's go with it!
