### ISSUE TITLE
About: Remove collaboration section and hard coded title from about page 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/boston-civic-media#28]
related to #27

The collaborations section need copy editing and framing for users to better understand: 

1. who these people are
2. what this section is trying to convey to the user (moving this inside the about/get involved page helps, but would still benefit from a sentence or 2, see get involved mockup for an example) 
3. having a purpose other than just telling people what happened (such as linking out to these projects or being able to see this information/papers) 

mostly a copy question. [see google copy doc for more info and copy](https://docs.google.com/a/elab.emerson.edu/document/d/11CX6VEDseO77IEB_O9lmvUBgw5U-j0b7coGOuTK_FdA/edit?usp=sharing)

**Comment by kanarinka** [comment]
You can remove this section from the website for the moment

**Comment by jpailthorpe** [comment]
Updated about page to remove collab section.

**Comment by jpailthorpe** [comment]
collab section still showing on about page for some reason
