### ISSUE TITLE
Eventspage: when there are no upcoming events listed in cms, hide upcoming events +Featured event div to match mockup

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/boston-civic-media#29]
[Current mockup: ](https://zpl.io/1soawS)

I'm slightly concerned that if there isn't any featured event, this section will be blank and strange, especially since upcoming events would also be blank, leaving a page that only displays a list of past events with no context. 

This is a mock without any upcoming events: 
![screen shot 2017-05-22 at 1 05 29 pm](https://cloud.githubusercontent.com/assets/10051544/26320040/662a0d3c-3eef-11e7-869d-085535383d3c.png)

On the one hand this is generally intuitive (we do events, there are no current events so you only see past events...),  but I think it is beneficial to include a header/sub-header just like the get involved page or the course page which explains a little bit about what events generally are (twitter chats, conference meetups, small hackathons, etc.) so that even if there aren't any events, they know what could be. We then we forward them to sign up for the newsletter but placing a link or by replacing the empty section with the sign up button.

**Comment by kanarinka** [comment]
I think it's fine to just show past events if there are no upcoming events.

**Comment by jpailthorpe** [comment]
Will go along with @kanarinka confirmation, changed title to make sure this is implemented and assigned to johnny.
