### ISSUE TITLE
About page copy:Update header copy to include missing words + correct link

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/boston-civic-media#31]
Aidan noticed some typos in "about" section paragraph, but i think these had to do mostly with the fact that the links in the last sentence weren't appearing, hiding the alt text that appears. 

"To learn more, read about some of the local collaborations that have formed from the network, notably an effort to create a Community IRB for collaborative, participatory research in Boston."

I think by just adding in the appropriate alt text that should appear where these links are it would fix the problem 

See #15 for more context.

**Comment by kanarinka** [comment]
Please correct any typos

**Comment by jpailthorpe** [comment]
updated about mockup to include new complete sentence
