### ISSUE TITLE
Lightning Talks: Eliminate separate additional page for each lightning talk due to lack of content/duplicate content

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/boston-civic-media#38]
I reviewed all 34 lightning talks currently in the cms. of these 34, only 3 had additional text content on their "more information" pages, and all other videos either had no content at all or duplicated content in the main list. these three instances have copy that is either found in other places on the site, speaker bio information that can be linked out if necessary, and/or info that can be placed in the vimeo description field on vimeo itself.  I suggest eliminating these pages and honing those three longer content blocks down into more digestable information like the other talks:

example of video with more information than listed on main page:
![screen shot 2017-05-23 at 12 29 10 pm](https://cloud.githubusercontent.com/assets/10051544/26365115/9e98a596-3fb4-11e7-82b4-6fc47730e829.png)
![screen shot 2017-05-23 at 12 28 55 pm](https://cloud.githubusercontent.com/assets/10051544/26365124/a4485022-3fb4-11e7-9fe8-93cc14cf2c9d.png)

The better way to do this is to include that information in the vimeo video description itself on vimeo, since it is almost like a built in "additional information" page, and more understood from a user perspective. 

This combined with the new layout which makes watching the videos much easier right on our page, and more space for longer descriptions right under the video if you need it, will help condense the bloat of content not getting updated/lost in the site. I have found a few videos that don't include more information due to not updating content. This would eliminate this worry. 

![screen shot 2017-05-23 at 12 40 14 pm](https://cloud.githubusercontent.com/assets/10051544/26365250/08af395e-3fb5-11e7-9cf8-babeade5b684.png)
![screen shot 2017-05-23 at 12 40 26 pm](https://cloud.githubusercontent.com/assets/10051544/26365251/08b32582-3fb5-11e7-836c-5d4fa7ae2949.png)

**Comment by kanarinka** [comment]
I fully support this change. Do you need help moving the content into Vimeo descriptions? If so, Becky can help with that.
