### ISSUE TITLE
Syllabi page - menus retaining state

### ISSUE THREAD

**Issue by kanarinka** [engagementgamelab/boston-civic-media#5]
Can the menus on the syllabi page show the state (i.e. the thing the person selected) so that it's clear how it's being filtered?

**Comment by kanarinka** [comment]
As a stop gap if that is hard and we can't get it in for this time around then could you add a "Clear all" link next to the filters so that people can easily get back to everything?

**Comment by esalling23** [comment]
Dropdowns now update to show selected filter and a reset button has been added
