### ISSUE TITLE
Remove boston civic media logo from footer of new site

### ISSUE THREAD

**Issue by kanarinka** [engagementgamelab/boston-civic-media#50]
The footer of the new site has the BCM logo surrounded by the elab and Teagle logos which is a little confusing. Becky and I would like to remove the BCM logo and just keep the other 2 to indicate that those are funders/sponsors. @jpailthorpe maybe you figure out the best person to assign this to?

**Comment by johnnycrich** [comment]
@jpailthorpe want me to handle this?

**Comment by jpailthorpe** [comment]
Sure

**Comment by kanarinka** [comment]
Please also remove the + +
