### ISSUE TITLE
home: subheader in boxes a bit small on desktop

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/boston-civic-media#54]
here is a side by side of the current site and a pop out of the mockup from zepplin:
![screen shot 2017-05-30 at 3 55 26 pm](https://cloud.githubusercontent.com/assets/10051544/26602143/7c7b0110-4550-11e7-9b0a-29d346580f5e.png)

I think a lot of this has to due with different bootstrap overrides and such. But we will need to make sure specifically text styles are updated with correct values and padding is not being accidently applied 
1024 desktop size: 

- [x] feature box header font size should be 1.75em 
- [x] feature box padding between boxes should be 16px, while boxes + padding should be 944 with 40px margins. 
- [x] feature boxes should be 304x236

granted i understand the bootstrap columns are not setup accurately in the mockups due to gutter width being not factored in on both sides, so I'm not specifically asking for exact dimensions here with those boxes, but if we can get them to feel a bit closer to the mock that would be great.

**Comment by jpailthorpe** [comment]
Not sure why the small cap styling was removed, but by doing that it messed with our sizing design. so this needs to be re-addressed at some point, but too late to change now.

**Comment by jpailthorpe** [comment]
maybe make the subheader feature text 1.1em?

**Comment by esalling23** [comment]
fixed in next build

**Comment by jpailthorpe** [comment]
fixed, ready for production.
