### ISSUE TITLE
Lightning Talks: Reword content (titles and short descriptions) to fit length limits

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/boston-civic-media#56]
<img width="935" alt="screen shot 2017-05-31 at 12 17 46 pm" src="https://cloud.githubusercontent.com/assets/11821504/26642269/2f4e24d4-45fb-11e7-9b57-841623dff20c.png">

Titles should be UNDER 100 characters. 
Descriptions should be UNDER 300 characters. 
Going over will cause layout issues.

**Comment by kanarinka** [comment]
Can you all please coordinate with Becky on this? She and/or Sean would be the right folks to contact about it.

**Comment by xina18** [comment]
I will work on this today.

**Comment by xina18** [comment]
This is done! Revised text appears in this doc and is reflected in Titles and Short Descriptions fields on Keystone. https://docs.google.com/document/d/1KxCj6JhMeIrtl_3R7QALt7WlvF_GDN6Sv1ls66vB7CA/edit
