### ISSUE TITLE
lightningtalks: padding between talks on bigger sized screens becomes inconsistent (text runs into blocks) 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/boston-civic-media#63]
not a priority for tomorrow, but figured id log. just gets a little sloppy. 

here is comment from @kanarinka :

"The videos and descriptive text are all bunched together and make it look messy and unclear whether the text that goes with each video is above or below the video. There are also a couple videos that are different aspect ratios and pushing down into the next row. So 2 ways to address:

Put at least 30-40px between rows of videos to give them space to breathe and make the page less overwhelming.
Make sure that different aspect ratios don't push into next row"

<img width="1204" alt="screen shot 2017-06-01 at 11 37 35 pm" src="https://cloud.githubusercontent.com/assets/10051544/26709801/63df82f0-4723-11e7-89de-e342a2976995.png">

**Comment by johnnycrich** [comment]
I'm adding a 40px to bottom of each video block.
