### ISSUE TITLE
Events: page content not wrapped within 1024 width 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/boston-civic-media#66]
text elements stretch to margins, needs to be contained like other page elements across the site and match mock.

**Comment by jpailthorpe** [comment]
<img width="1680" alt="screen shot 2017-06-02 at 1 32 40 pm" src="https://cloud.githubusercontent.com/assets/10051544/26737405/fb21e9c2-4797-11e7-85e9-65d791311cc7.png">

this is still happening. basically want that text to wrap instead of the whole element stretching when the window is large

**Comment by jpailthorpe** [comment]
moving to ice not a big deal

**Comment by jpailthorpe** [comment]
this is still happening, though again, not a big deal.

**Comment by esalling23** [comment]
fixed for next build

**Comment by jpailthorpe** [comment]
Still a little wonky, since the min 1200 breakpoint create a smaller width than when it is below that (hard to explain) but it is not the end of the world, and better than it was for sure. I am going to move this to done since it solved the main problem.
