### ISSUE TITLE
Courses page: Title should not be "Boston Civic Media"

### ISSUE THREAD

**Issue by kanarinka** [engagementgamelab/boston-civic-media#70]
The title on the courses page should be something like "11 Courses Tackle Climate Change in 2017-18" or, if we want it less headliney, "Climate Change Courses 2017-18"

**Comment by jpailthorpe** [comment]
this is what it will look like:

<img width="807" alt="screen shot 2017-06-02 at 10 11 04 am" src="https://cloud.githubusercontent.com/assets/10051544/26729510/d66d14b0-477b-11e7-8980-8cceecc5ea50.png">

**Comment by jpailthorpe** [comment]
please confirm if you want this changed @kanarinka

**Comment by jpailthorpe** [comment]
this screenshot is now what shows as live on qa. the title " 2017-2018 consortium course catalog" can be edited in keystone, but the "boston civic media" header is hard coded. This was Aidan's design originally. I think this works great, but let us know if we need to change the title soon
