### ISSUE TITLE
Events: new BCM climate change event image becoming pixelated via cloundinary url

### ISSUE THREAD

**Issue by kanarinka** [engagementgamelab/boston-civic-media#72]
On the home page under events, the image for civic imagination seems to only be a grey background. We should put a better, more exciting image there.

**Comment by jpailthorpe** [comment]
@kanarinka this is the only image i have that represents the conference. This is changable in keystone under the event when you add one. If @aidanrae or @codeworthy has a better image we can put it in keystone.

**Comment by jpailthorpe** [comment]
@aidanrae is making a new image for this today, but note that we don't have any current image we use to represent the conference other than the one on the site right now. in the future, this should be better addressed.

**Comment by aidanrae** [comment]
![bcm keynote](https://cloud.githubusercontent.com/assets/6587766/26735810/755b85ba-4791-11e7-8fff-720471231c0a.png)

**Comment by aidanrae** [comment]
I don't have much imagery, just the low-res headshots the speakers sent and the assets I made for the splashthat/swag backgrounds, so let me know if this works

**Comment by jpailthorpe** [comment]
uploaded to keystone: 

that cloudinary thing is happening again though. the width restraints in the url are creating pixelation. removing them and putting the contraints in the css fixes it, though i know you have done this before and im sure you have a better way. just did this to show you

<img width="1551" alt="screen shot 2017-06-02 at 1 21 30 pm" src="https://cloud.githubusercontent.com/assets/10051544/26737053/8b4e0212-4796-11e7-914f-dbb3e2a28c94.png">
<img width="1509" alt="screen shot 2017-06-02 at 1 21 23 pm" src="https://cloud.githubusercontent.com/assets/10051544/26737078/9eced79e-4796-11e7-8fc9-ec178f9fd504.png">

**Comment by jpailthorpe** [comment]
Also @aidanrae should the home page event photo have a greyscale filter on it?

**Comment by johnnycrich** [comment]
@jpailthorpe we can't remove the width constraint for loading an image that big, otherwise the entire 1000px image is loaded.

**Comment by johnnycrich** [comment]
The image should also not be PNG.

**Comment by jpailthorpe** [comment]
fine with me!

**Comment by jpailthorpe** [comment]
this has been fixed.
