### ISSUE TITLE
Get Involved Page: Join the Listserv section needs design tweaking

### ISSUE THREAD

**Issue by kanarinka** [engagementgamelab/boston-civic-media#74]
It's not very legible. For a short term quick fix, I suggest left-aligning everything and putting more line-height between lines of text. Looks like the .subheader class is causing some of these issues but when I took it off then the text seemed too small. I would keep the text at least 16px.

**Comment by jpailthorpe** [comment]
#62 duplicate. added additional info provided by @kanarinka into that issue. its in icebox since out of scope.
