### ISSUE TITLE
Lightning Talks Page: small issues

### ISSUE THREAD

**Issue by kanarinka** [engagementgamelab/boston-civic-media#80]
3 things - 
1) Change the title of the page to "Lightning Talks" instead of "Lightning Talk Archive"
2) There needs to be more space between the title and "Browse the talks below..."
3) Change "Use the filter buttons below to sort talks by category or event." to "Use the filter buttons below to sort talks by category."

**Comment by jpailthorpe** [comment]
these are def. tweaks that should be addressed to match the mockup in zeplin. putting in icebox near top since no blockers but most likely wont hit on this iteration.
