### ISSUE TITLE
Courses: Content missing from document, please post info in this comment 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/boston-civic-media#86]
this is what i am missing:

- [x] Wheelock school contact information 
- [ ] no email listed for doris sommer
- [x] all of harvard's enrollment information. This entire block is missing. unsure what to do without it. 

this is what i edited. you can make changes directly in keystone:

- [ ] rahul's data storytelling course description (for length) 
- [ ] arts health course at harvard course description for length ( it was out of control)

**Comment by gmugar** [comment]
contact for doris sommer is a URL: https://scholar.harvard.edu/dsommer/contact_owner
harvard cross registration info: https://courses.harvard.edu/crossregistration.html

**Comment by gmugar** [comment]
Wheelock: 
- registrar@wheelock.edu
- 617-879-2135

**Comment by jpailthorpe** [comment]
I added wheelock info and harvard website url. I just grabbed some info from the harvard site, but you can edit what you like in keystone. 

We can't have a http link for the email since it uses a specific model that wants a mailto link. Can't have both in same model, so we either need an email or we leave it blank. We can add this link to her email form and a brief explanation in the enrollment info if you like. You can just add it in keystone under enrollment info for harvard. 

I also can't figure out the official name for harvard registration (so i just named it Harvard University Cross Registration) and can't find a phone number or email to the office. sorry I did try to find it! If you want to add this, you can in keystone under courses>arts and global health.
