### ISSUE TITLE
Header: Change "Courses" to "Climate Courses"

### ISSUE THREAD

**Issue by kanarinka** [engagementgamelab/boston-civic-media#94]
We think there might be confusion between courses and syllabi in the header. We'd like to rename "Courses" to "Climate Courses"

**Comment by esalling23** [comment]
@jpailthorpe  @kanarinka 
Would this apply to the navigation bar and the "Course Name"/"Course Listing" headers on the courses page? The current page header is in Keystone, and reads "2017-2018 Consortium Course Catalog"

**Comment by kanarinka** [comment]
Just the navigation bar - thanks!

---
Assistant Professor of Civic Media and Data Visualization, Emerson College
Fellow, Emerson Engagement Lab
Research Affiliate, MIT Center for Civic Media
www.kanarinka.com | @kanarinka | 617-501-2441

**Comment by jpailthorpe** [comment]
fixed and confirmed working. ready for prod

**Comment by jpailthorpe** [comment]
Up on production
