### ISSUE TITLE
Courses: mailto model for contact info under courses view needs to replace the contacturl model

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/boston-civic-media#97]
computer is dumb for some reason and I can't push (not a big deal just fyi). but this is what we need to change.

![screen shot 2017-06-08 at 12 46 22 pm](https://user-images.githubusercontent.com/10051544/26940458-bcb0949e-4c48-11e7-9eb2-dea0d2748792.png)

**Comment by esalling23** [comment]
fixed for next build

**Comment by jpailthorpe** [comment]
confirmed fixed on qa. ready for production
